### ISSUE TITLE
Renaming files also changes the content

### ISSUE THREAD

**Issue by dstadelm** [gabrielpoca/replacer.nvim#10]
**Given** populating the quickfix list with telescope find_files 
**When** running ```:lua require("replacer").run()<cr>```
**And** renaming the files
**Then** the contents of the first line of the renamed files also is modified

**Comment by gabrielpoca** [comment]
@dstadelm thank you for opening an issue! I can't replicate, can you provide more details?

**Comment by dstadelm** [comment]
Sorry for my delayed response. I was on vacation ;-)

Step 1: Selecting two files test1.txt and test2.txt containing the text as shown in the cat output

![image](https://user-images.githubusercontent.com/3010527/197700998-1d4a8907-437c-46fc-95ab-508578eff701.png)

Step2: `:lua require("replacer").run()<cr>`
![image](https://user-images.githubusercontent.com/3010527/197701178-1b7c29ed-80ac-4c26-aa59-50a076b3f129.png)

Step3: rename files
![image](https://user-images.githubusercontent.com/3010527/197701237-b6cc04eb-47b2-48fa-b521-eb806f7ef865.png)

Step 4:
Write quickfix buffer
![image](https://user-images.githubusercontent.com/3010527/197701368-09f88a47-746c-4519-813a-8f5d81dcae1d.png)

Step5: cat result
![image](https://user-images.githubusercontent.com/3010527/197701640-8fb8f00c-0117-431a-a28a-e7bc4f47b36c.png)

I assume it has something to do how the quickfix list is populated by telescope

**Comment by dstadelm** [comment]
It might be relevant, that I'm using Telescope find_files not live_grep

**Comment by gabrielpoca** [comment]
@dstadelm thank you! Yeah, that's expected, unfortunately, and I'm unsure how I would fix it. I'm parsing that text in the quickfix window, assuming the context of the contents of the line is on the right, which is not the case with `find_files` since it's not picking a line. So when I'm saving the changes, I replace the line because it's like you changed it. I need to investigate, but seems weird to me that it's showing the file name on the right as well
