### ISSUE TITLE
Replace in quickfix directly

### ISSUE THREAD

**Issue by Shatur** [gabrielpoca/replacer.nvim#2]
I would like to suggest to add the ability to edit things inside quickfix directly. There is an awesome [quickfix-reflector.vim](https://github.com/stefandtw/quickfix-reflector.vim) plugin the have similar functionality, but in Vimscript.

**Comment by gabrielpoca** [comment]
Yeah, I would love that, but as far as I know, in quickfix we cannot edit the path of the file, only the contents, right?

**Comment by Shatur95** [comment]
> Yeah, I would love that, but as far as I know, in quickfix we cannot edit the path of the file, only the contents, right?

No, file path is editable too :)

**Comment by gabrielpoca** [comment]
I guess that I need to look into it again 🧐  I remember there was a reason I didn't use it, but I may have missed something

**Comment by gabrielpoca** [comment]
I pushed a change that makes this plugin use the quickfix window and buffer instead of creating new ones. It's not exactly the same as quickfix-reflector because I still replace the lines of the quickfix window with a different format, but it allowed me to remove a lot of code that was only there to handle floating windows and borders. I'm not sure if that's what you were expecting, but I'm closing this for now.

**Comment by Shatur** [comment]
> It's not exactly the same as quickfix-reflector because I still replace the lines of the quickfix window with a different format

It would be nicer to keep the same format.

But this is a good news anyway!
